version: "3.9"

services:
  api:
    image: exalted_api
    ports:
      - "8000:8000"
    configs:
      - source: envfile
        target: /app/.env
    restart: on-failure

configs:
  envfile:
    file: ./.env.production