version: "3.9"

services:
  api:
    image: exalted_api
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./cache.bin
        target: /app/cache.bin
      - cdn:/app/cdn/
    configs:
      - source: envfile
        target: /app/.env
    restart: on-failure

configs:
  envfile:
    file: ./.env.production

volumes:
  cdn: